web-admin-sd/src/sd-web/urls.py
'''
(c) Copyright 2013 Telefonica, I+D. Printed in Spain (Europe). All Rights
Reserved.

The copyright to the software program(s) is property of Telefonica I+D.
The program(s) may be used and or copied only with the express written
consent of Telefonica I+D or in accordance with the terms and conditions
stipulated in the agreement/contract under which the program(s) have
been supplied.
'''
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('',
    url(r'^sd/web', include('web.urls', namespace='web')),
)

web-admin-sd/src/sd-web/web/urls.py
"""
(c) Copyright 2013 Telefonica, I+D. Printed in Spain (Europe). All Rights
Reserved.

The copyright to the software program(s) is property of Telefonica I+D.
The program(s) may be used and or copied only with the express written
consent of Telefonica I+D or in accordance with the terms and conditions
stipulated in the agreement/contract under which the program(s) have
been supplied.
"""

from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.conf import settings

from web.auth_views import LoginView
from web.views import HomeTemplateView, SearchCapTemplateView, SearchEndTemplateView, \
    CapabilitiesTemplateView, EndpointsTemplateView, AddCapFormView, CapabilitiesRemoveFormView,\
    CapabilityModificationFormView, AddEndpointFormView, EditEndpointFormView, RemoveEndpointFormView
from web.auth_views import LogoutView


urlpatterns = patterns('',
                       url(r'^(/?|/login/?)$', LoginView.as_view(), name='login'),
                       url(r'^/logout/?$', LogoutView.as_view(), name='logout'),
                       url(r'^/home/?$',
                           login_required(function=HomeTemplateView.as_view(),
                                          login_url=settings.LOGGING_URL),
                           name='home'),

                       url(r'^/searchCap/?$',
                           login_required(function=SearchCapTemplateView.as_view(),
                                          login_url=settings.LOGGING_URL), name='searchCap'),
                       url(r'^/searchEnd/?$',
                           login_required(function=SearchEndTemplateView.as_view(),
                                          login_url=settings.LOGGING_URL), name='searchEnd'),

                       # url(r'^(addCap/?)$', AddCapTemplateView.as_view(), name='addCap'),
                       url(r'^/addCap/?$',
                           login_required(function=AddCapFormView.as_view(),
                                          login_url=settings.LOGGING_URL), name='addCap'),

                       url(r'^/capabilities/?$',
                           login_required(function=CapabilitiesTemplateView.as_view(),
                                          login_url=settings.LOGGING_URL), name='capabilities'),


                       url(r'^/capabilities/endpoints/removeEnd/?$',
                           login_required(function=RemoveEndpointFormView.as_view(),
                                          login_url=settings.LOGGING_URL), name='remEndpoints'),


                       url(r'^/(?P<api_name>[a-zA-Z0-9_-]+)/(endpoints/?)',
                           login_required(function=EndpointsTemplateView.as_view(),
                                          login_url=settings.LOGGING_URL), name='endpoints'),


                       url(r'^/capabilities/remove/?$',
                           login_required(function=CapabilitiesRemoveFormView.as_view(),
                                          login_url=settings.LOGGING_URL), name='removeCapabilities'),

                       url(r'^/(capabilities/addEnd?)$',
                           login_required(function=AddEndpointFormView.as_view(),
                                          login_url=settings.LOGGING_URL), name='addEndpoint'),

                       url(r'^/(capabilities/editEnd?)$',
                           login_required(function=EditEndpointFormView.as_view(),
                                          login_url=settings.LOGGING_URL),
                           name='editEndpoint'),

                       url(r'^/(editCap/?)$',
                           login_required(function=CapabilityModificationFormView.as_view(),
                                          login_url=settings.LOGGING_URL), name='modifyCapSubmit'),

)

web-admin-sd/src/sd-web/web/templates/addCap.html
{% extends "main_frame.html" %}
{% block content %}
{% load staticfiles %}

    <form id="mainForm" action="addCap" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>Fill to add a new Capability</legend>
            <div class="row-fluid">
                <div class="span2"></div>
                <div class="span4">

                    <label>Capability Name</label>
                    <input id="api_name" name="api_name" type="text" placeholder="Capability Name"/>
                    <label>Description</label>
                    <input id="description" name="description" type="text" placeholder="Description"/>
                </div>
                <div class="span1"></div>
                <div class="span5">
                    <label>Default Version</label>
                    <input id="default_version" name="default_version" type="text" placeholder="1.0.0"/>
                    <br/>

                    <br/>
                    <input id="id_submit" type="button" class="btn btn-large btn-primary openAlertDialog" value="Submit"/>
                </div>
            </div>
        </fieldset>
        <br>

    </form>

    <div class="alert alert-block alert-error" style="display: none">
        <a class="close" data-hide="alert">×</a>
        <h4 class="alert-heading">You are going to save a new capability. Do you want to save it?</h4><br>
        <p>
             <a id="save" class="btn btn-danger submitMainForm" >Save Capability</a>&nbsp;&nbsp;
             <a id="cancel" class="btn btn-info" data-hide="alert">Cancel</a>
        </p>
    </div>

{%  endblock %}

{% block scripts %}
    <script src="{% static "js/addCap-main.min.js" %}"></script>
{% endblock %}

web-admin-sd/src/sd-web/web/templates/capabilities.html
{% extends "main_frame.html" %}
{% block content %}
{% load url from future %}
{% load staticfiles %}

    <div class="row-fluid">
        <div class="span12">
            <h2 id="title-capabilities" class="text-center">Capabilities</h2>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th id="column-title-capability">Capability</th>
                        <th id="column-title-description" class="hidden-phone">Description</th>
                        <th id="column-title-default-version">Default Version</th>
                        <th id="column-title-options">Options</th>
                    </tr>
                </thead>
                <tbody>
                {% for capability in capabilities %}
                    <tr>
                        <td><a class="normalLink" href="{{ capability.web_href }}">{{ capability.api_name }}</a></td>
                        <td class="hidden-phone">{{ capability.description }}</td>
                        <td>{{ capability.default_version }}</td>
                        <td api_name="{{ capability.api_name }}" description="{{ capability.description }}" default_version="{{ capability.default_version }}">
                            <a id="add-endpoint-{{capability.api_name}}" class="btn btn-mini btn-primary showAddEndModal" ><i class="icon-plus icon-white"></i></a>
                            <a id="edit-{{capability.api_name}}" class="btn btn-mini btn-primary showEditCapModal" ><i class="icon-pencil icon-white"></i></a>
                            <a id="remove-{{capability.api_name}}" class="btn btn-mini btn-primary showRemoveCapModal" ><i class="icon-minus icon-white"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>


    <!-- Add Endpoint Modal -->
    <div id="addEndpointModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel"></h3>
        </div>
        <div class="modal-body">
            <form id="addEndForm" action="capabilities/addEnd" method="post">
                {% csrf_token %}
                <input id="apiNameField"  name="api_name" type="hidden">
                <div class="span4">
                    <label>Environment</label>
                    <div class="input-append">
                        <input class="span11" id="environmentTextField" name="environment" type="text">
                        <div class="btn-group">
                            <ul class="dropdown-menu">
                                <li><a class="envItem" item="production" style="cursor: pointer">production</a></li>
                                <li><a class="envItem" item="preproduction" style="cursor: pointer">preproduction</a></li>
                                <li><a class="envItem" item="integration" style="cursor: pointer">integration</a></li>
                                <li><a class="envItem" item="development" style="cursor: pointer">development</a></li>
                            </ul>
                            <button class="btn dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>

                        </div>
                    </div>
                    <label>Version</label>
                    <input id="endpoint-version" type="text" name="version" placeholder="Version Number">
                    <label>Url</label>
                    <input id="endpoint-url" type="text" name="url" placeholder="Url">
                </div>
                <div class="span1"></div>
                <div class="span5">
                    <label>OB</label>
                    <input id="endpoint-ob" type="text" name="ob" placeholder="OB identifier">

                    <br/>
                    <br/>
                    <label class="checkbox">
                        <input id="endpoint-premium" type="checkbox" name="premium"> Premium
                    </label>
                    {# <label class="checkbox"> #}
                        {# <input type="checkbox"> Set as Default Version.  #}
                    {# </label> #}
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button id="close-add-endpoint" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button id="add-endpoint" class="btn btn-primary submitAddEndForm" >Add Endpoint</button>
        </div>
    </div>

    <!-- Edit Capability Modal -->
    <div id="editCapabilityModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="editCapModalLabel"></h3>
        </div>
        <div class="modal-body">
            <form id="editForm" action="editCap" method="post">
                {% csrf_token %}
                <input id="apiNameFieldEdit" name="api_name" type="hidden">
                <div class="row-fluid">
                    <div class="span1"></div>
                    <div class="span4">

                        <label>Description</label>
                        <input id="editDescriptionField" name="description" type="text" placeholder="Description">
                    </div>
                    <div class="span1"></div>
                    <div class="span5">
                        <label>Default Version</label>
                        <input id="editVersionField" name="default_version" type="text" placeholder="1.0.0">
                        {# <input type="submit" class="btn btn-large btn-primary" value="Submit">  #}
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button id="close-edit-capability"  class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button id="edit-capability" class="btn btn-primary submitEditForm" >Edit Capability</button>
        </div>
    </div>

    <!-- Remove Capability Modal -->
    <div id="removeCapModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="removeCapModalLabel"></h3>
            <form id="removeForm" method="post" action={% url 'web:removeCapabilities' %}>
                {% csrf_token %}
                <input id="capabilityRemoveField" type="hidden" name="api_name">
            </form>
        </div>
        <div class="modal-body">
            <p class="text-center">Are you sure?</p>
        </div>
        <div class="modal-footer">
            <button id="close-del-capability" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button id="del-capability" class="btn btn-danger deleteCapability" >Remove Capability</button>
        </div>
    </div>


{%  endblock %}


{% block scripts %}
    <script src="{% static "js/capabilities-main.min.js" %}"></script>
{% endblock %}

web-admin-sd/src/sd-web/web/templates/empty_template.html
{% extends "main_frame.html" %}
{% block content %}
{% load staticfiles %}

<p>{{ title }}</p>
<img src="{% static "images/telefonica.png" %}" alt="My image"/>
{%  endblock %}

web-admin-sd/src/sd-web/web/templates/endpoints.html
{% extends "main_frame.html" %}
{% block content %}
{% load staticfiles %}

     <div class="row-fluid">
        <div class="span12">
            <h2 id="title-endpoints" class="text-center">Endpoints of {{ api_name }}</h2>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th id="column-title-url">URL</th>
                        <th id="column-title-version">Version</th>
                        <th id="column-title-environment" class="hidden-phone">Environment</th>
                        <th id="column-title-ob" class="hidden-phone">OB</th>
                        <th id="column-title-premium" class="hidden-phone">Premium</th>
                        <th id="column-title-options">Options</th>
                    </tr>
                </thead>
                <tbody>
                {% for endpoint in endpoints %}
                    <tr>
                        <td><a class="linkStyled" id="{{ endpoint.id }}">{{ endpoint.url }}</a></td>
                        <td>{{ endpoint.version }}</td>
                        <td>{{ endpoint.environment }}</td>
                        <td class="hidden-phone">{{ endpoint.ob }}</td>
                        <td class="hidden-phone">
                            {% if endpoint.premium %}
                                <i class="icon-ok icon"></i>
                            {% else %}
                                <i class="icon-remove icon"></i>
                            {% endif %}
                        </td>
                        <td end_id="{{ endpoint.id }}" api_name="{{ api_name }}" version="{{ endpoint.version }}" environment="{{ endpoint.environment }}" url="{{ endpoint.url }}" ob="{{ endpoint.ob }}" premium="{% if endpoint.premium %}true{% else %}false{% endif %}" >
                            <a id="edit-{{ endpoint.id }}" class="btn btn-mini btn-primary showEditEndModal" ><i class="icon-pencil icon-white"></i></a>
                            <a id="del-{{ endpoint.id }}" class="btn btn-mini btn-primary showRemoveEndModal" ><i class="icon-minus icon-white"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>


    <!-- Edit Endpoint Modal -->
    <div id="editEndpointModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="editEndModalLabel"></h3>
        </div>
        <div class="modal-body">
            <form id="editForm" action="../capabilities/editEnd" method="post">
                {% csrf_token %}
                <input id="apiNameField" type="hidden" name="api_name">
                <input id="idEndField" type="hidden" name="id_end">
                <div class="row-fluid">
                    <div class="span4">
                        <label>Environment</label>
                        <div class="input-append">
                            <input class="span11" id="environmentTextField" name="environment" type="text">
                            <div class="btn-group">
                                <ul class="dropdown-menu">
                                    <li><a class="envItem" item="production" style="cursor: pointer">production</a></li>
                                    <li><a class="envItem" item="preproduction" style="cursor: pointer">preproduction</a></li>
                                    <li><a class="envItem" item="integration" style="cursor: pointer">integration</a></li>
                                    <li><a class="envItem" item="development" style="cursor: pointer">development</a></li>
                                </ul>
                                <button class="btn dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>

                            </div>
                        </div>
                        <label>Version</label>
                        <input id="versionField" type="text" name="version" placeholder="Version Number">
                        <label>Url</label>
                        <input id="urlField" type="text" name="url" placeholder="Url">
                    </div>
                    <div class="span1"></div>
                    <div class="span5">
                        <label>OB</label>
                        <input id="obField" type="text" name="ob" placeholder="OB identifier">

                        <br/>
                        <br/>
                        <label id="premiumCheckBox" class="checkbox">
                            <input id="premiumField" type="checkbox" name="premium"> Premium
                        </label>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button id="close-edit-endpoint" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button id="edit-endpoint" class="btn btn-primary submitEditForm" >Edit Endpoint</button>
        </div>
    </div>

    <!-- Remove Endpoint Modal -->
    <div id="removeEndModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="removeEndModalLabel"></h3>
        </div>
        <div class="modal-body">
            <p class="text-center">Are you sure?</p>
            <form id="deleteForm" action="/sd/web/capabilities/endpoints/removeEnd" method="post">
                {% csrf_token %}
                <input id="apiNameRemoveField" type="hidden" name="api_name">
                <input id="idEndRemoveField" type="hidden" name="id_end">
            </form>
        </div>
        <div class="modal-footer">
            <button id="close-del-endpoint" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button id="del-endpoint" class="btn btn-danger deleteEndpoint" >Remove Endpoint</button>
        </div>
    </div>

{%  endblock %}


{% block scripts %}
    <script src="{% static "js/endpoints-main.min.js" %}"></script>
{% endblock %}

web-admin-sd/src/sd-web/web/templates/footer.html
{% load staticfiles %}
<div id="footer">
  <div class="row-fluid">
    <div class="span12">
        <p class="pull-left" id="footer-text" >&copy; Telef&oacute;nica 2013</p>
        <img id="footer-image" src="{% static "images/telefonica.png" %}" class="pull-right" alt="My image"/>
    </div>
  </div>
</div>

web-admin-sd/src/sd-web/web/templates/form_result.html
{% extends "main_frame.html" %}
{% load  getitem_tag %}
{% block content %}
{% load staticfiles %}

<p>{{ title }}</p>
{% if body %}
    <p>Error_Code: {{ body|getitem_tag:"error_code" }}</p>
    <p>Description: {{ body|getitem_tag:"description" }}</p>
{% endif %}

{%  endblock %}

web-admin-sd/src/sd-web/web/templates/login.html
{% load get_error_form %}
{% load staticfiles %}
{% spaceless %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <title>Sign in &middot; Service Directory</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">


    <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">

    <link href="{% static "styles/responsive.css" %}" rel="stylesheet">
    <link href="{% static "styles/sd-login-style.css" %}" rel="stylesheet">

</head>

<body>

    <div id="wrap">
        <div class="container">
            <h1 class="login-title text-center">Service Directory Login</h1>

            <div class="hero-unit">
                <form class="form-signin" id="login" action="" method="post">
                    {% csrf_token %}
                    <input name="username" id="username" type="text" class="input-block-level" placeholder="username">
                    <input name="password" id="password" type="password" class="input-block-level" placeholder="Password">
                    <br>
                    <br>
                    <div>
                        <button id="sign-in" class="btn btn-large btn-primary" type="submit">Sign in</button>
                        <div class="login-error">
                            {% if form != None %}
                                {{form|get_error_form}}
                            {% endif %}
                        </div>
                    </div>
                </form>
            </div>

        </div>

        <div id="push"></div>
    </div>
    {% include 'footer.html' %}


    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

</body>
</html>
{% endspaceless %}

web-admin-sd/src/sd-web/web/templates/main_frame.html
{% load staticfiles %}
{% load url from future %}
{% spaceless %}


<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "styles/responsive.css" %}" rel="stylesheet">
    <link href="{% static "styles/sd-style.css" %}" rel="stylesheet">
</head>

<body>

    <div id="wrap">
        <div class="navbar navbar-inverse navbar-static-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <ul class="nav pull-left">
                        <li><a class="" href={% url 'web:home' %}><b style="font-size: 20">Service Directory</b></a></li>
                    </ul>
                    <div class="nav-collapse collapse">
                        <ul class="nav">

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-search icon-white"></i> Search <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href={% url 'web:searchCap' %}><i class="icon-search icon"></i> Search Capability</a></li>
                                    <li><a href={% url 'web:searchEnd' %}><i class="icon-search icon"></i> Search Endpoint</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-wrench icon-white"></i> Management<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href={% url 'web:addCap' %}><i class="icon-plus icon"></i> Add Capability</a></li>
                                    {% comment %}<li><a href="addEnd"><i class="icon-plus icon"></i> Add Endpoint</a></li>
                                    <li><a href="removeCap"><i class="icon-minus icon"></i> Remove Capability</a></li>
                                    <li><a href="removeEnd"><i class="icon-minus icon"></i> Remove Endpoint</a></li>{% endcomment %}
                                </ul>
                            </li>
                            <li>
                                <a href={% url 'web:capabilities' %}><i class="icon-th-list icon-white"></i> Capabilities</a>
                            </li>
                        </ul>
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> {{user.username}}<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href={% url 'web:logout' %}><i class="icon-off icon"></i> Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div><!-- nav-collapse collapse -->
                </div> <!-- Container -->
            </div> <!-- navbar-inner -->
        </div>
        <div class="container-fluid" style="padding-top: 20px;">
            <div class="row-fluid">
                <div class="hero-unit">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
        <div id="push"></div>
    </div>
    {% include 'footer.html' %}
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    {% block scripts %}  {% endblock %}
</body>
</html>
{% endspaceless %}